import {StyleSheet} from 'react-native';
import Color from '../../constants/Colors'
import layout from '../../constants/Layout'

export const styles = StyleSheet.create({
  overlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    height: layout.window.height,
    right: 0,
    backgroundColor: '#000',
    opacity: 0.5,
    zIndex: 99,
  },
  modalContainer:{
    backgroundColor: '#b5a8b7',
    marginTop: 100,
    height: 350,
    margin: 40,
    position: 'absolute',
    width: layout.window.width/1.2,
    zIndex: 100,
    borderRadius: 30
  },
  textarea: {
    backgroundColor: '#ececec',
    borderRadius: 20,
    color: Color.titleColor,
    fontSize: 20,
    height:150,
    padding: 10,
    paddingBottom: 30,
    textAlign: 'center',
    width: 250,
  },
  idea: {
    height: 100,
    borderBottomColor: '#ececec',
    borderBottomWidth: 1,
    borderStyle: 'solid',
    color: '#ececec',
    fontSize: 23,
    padding: 20,
    margin: 15,
    textAlign: 'center',
    marginBottom: 30,
  },
  ideaSemanal: {
    height: 100,
    borderBottomColor: '#ececec',
    borderBottomWidth: 1,
    borderStyle: 'solid',
    color: '#ececec',
    fontSize: 23,
    padding: 35,
    margin: 15,
    textAlign: 'center',
    marginBottom: 30,
  },
  buttonContainer: {
    alignItems: 'center',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 70
  },
  deleteButton: {
    backgroundColor: '#ececec',
    borderRadius: 10,
    color: 'gray',
    fontSize: 25,
    height: 40,
    margin: 20,
    padding: 7,
    textAlign: 'center',
    width: 40,
  },
  saveButton: {
    height: 40,
    width: 150,
    fontSize: 20,
    borderColor: '#ececec',
    backgroundColor: '#ececec',
    borderRadius: 10,
    textAlign: 'center',
    paddingTop: 5,
    color: Color.deleteGoal,
    margin: 10,
  },
  buttonSavePressed: {
    backgroundColor: 'gray',
    height: 40,
    width: 150,
    fontSize: 20,
    borderRadius: 10,
    textAlign: 'center',
    paddingTop: 5,
    color: '#efccec'
  }
})